### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by 5an1ty** [prolina-foundation/lisk-nomo#1]
When trying to toggle forging we should check if the node supports API over https (or as a configuration option).

**Comment by webmaster128** [comment]
Should be fixed on current master (https://github.com/prolina-foundation/lisk-nomo/commit/05f6e96d503427bee4561eb77ccb0d4bab4c4250)

**Comment by webmaster128** [comment]
Fixed on current master and tested by @5an1ty. Thanks! Closing.
